# -*- coding: utf-8 -*-
"""trabalho.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHqhzCyhEW2eoHwa2U5Ia3LbqbRXv9wI
"""

from urllib.parse import urlparse

from fastapi import FastAPI, HTTPException, Query

app = FastAPI(

)


PAGINAS = [
    {
        "url": "https://exemplo.com",
        "status_code": 200,
        "content_type": "text/html; charset=utf-8",
        "titulo": "Exemplo - Página Inicial",
        "descricao": "Página inicial do site de exemplo.",
        "h1": ["Bem-vindo ao Exemplo"],
        "h2": ["Sobre nós", "Serviços", "Contato"],
        "links": [
            {"texto": "Sobre", "url": "https://exemplo.com/sobre"},
            {"texto": "Produtos", "url": "https://exemplo.com/produtos"},
            {"texto": "Contato", "url": "https://exemplo.com/contato"},
        ],
        "imagens": [
            "https://exemplo.com/img/logo.png",
            "https://exemplo.com/img/banner.jpg",
        ],
        "texto": "Bem-vindo ao Exemplo. Somos uma empresa fictícia que oferece "
        "diversos serviços para clientes em todo o Brasil.",
    },
    {
        "url": "https://exemplo.com/sobre",
        "status_code": 200,
        "content_type": "text/html; charset=utf-8",
        "titulo": "Sobre - Exemplo",
        "descricao": "Conheça a história da empresa Exemplo.",
        "h1": ["Sobre nós"],
        "h2": ["Nossa história", "Nossa equipe"],
        "links": [
            {"texto": "Início", "url": "https://exemplo.com"},
            {"texto": "Contato", "url": "https://exemplo.com/contato"},
        ],
        "imagens": ["https://exemplo.com/img/equipe.jpg"],
        "texto": "A empresa Exemplo foi fundada em 2010 com o objetivo de "
        "simplificar a vida dos clientes.",
    },
    {
        "url": "https://exemplo.com/produtos",
        "status_code": 200,
        "content_type": "text/html; charset=utf-8",
        "titulo": "Produtos - Exemplo",
        "descricao": "Lista de produtos disponíveis.",
        "h1": ["Nossos produtos"],
        "h2": ["Mais vendidos", "Lançamentos"],
        "links": [
            {"texto": "Produto A", "url": "https://exemplo.com/produtos/a"},
            {"texto": "Produto B", "url": "https://exemplo.com/produtos/b"},
        ],
        "imagens": [
            "https://exemplo.com/img/produto-a.png",
            "https://exemplo.com/img/produto-b.png",
        ],
        "texto": "Confira o Produto A por R$ 49,90 e o Produto B por R$ 79,90.",
    },
    {
        "url": "https://api.exemplo.com/usuarios",
        "status_code": 200,
        "content_type": "application/json",
        "dados": [
            {"id": 1, "nome": "Ana Souza", "email": "ana@exemplo.com", "ativo": True},
            {"id": 2, "nome": "Bruno Lima", "email": "bruno@exemplo.com", "ativo": True},
            {"id": 3, "nome": "Carla Dias", "email": "carla@exemplo.com", "ativo": False},
        ],
    },
]



def normalizar_url(url: str) -> str:
    """Remove espaços e a barra final para facilitar a comparação."""
    return url.strip().rstrip("/")


def validar_url(url: str) -> None:
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise HTTPException(status_code=400, detail="URL inválida. Use http:// ou https://")


def buscar_pagina(url: str) -> dict:
    """Procura a URL na lista mockada."""
    validar_url(url)
    alvo = normalizar_url(url)
    for pagina in PAGINAS:
        if normalizar_url(pagina["url"]) == alvo:
            return pagina
    raise HTTPException(status_code=404, detail="URL não encontrada nos dados mockados.")



@app.get("/")
def raiz():
    return {
        "mensagem": "API no ar (modo mock). Use /ler?url=https://exemplo.com ou /docs",
        "urls_disponiveis": [p["url"] for p in PAGINAS],
    }


@app.get("/urls")
def listar_urls():
    """Lista todas as URLs disponíveis nos dados mockados."""
    return [
        {"url": p["url"], "content_type": p["content_type"]} for p in PAGINAS
    ]


@app.get("/ler")
def ler_pagina(
    url: str = Query(..., description="URL a ser lida, ex.: https://exemplo.com"),
    max_links: int = Query(100, ge=0, le=1000),
    max_texto: int = Query(5000, ge=0, le=100000, description="Máx. de caracteres do texto"),
):
    """Devolve em JSON os dados da página correspondente à URL."""
    pagina = buscar_pagina(url)


    if "dados" in pagina:
        return {
            "url": pagina["url"],
            "status_code": pagina["status_code"],
            "content_type": pagina["content_type"],
            "dados": pagina["dados"],
        }


    return {
        "url": pagina["url"],
        "status_code": pagina["status_code"],
        "content_type": pagina["content_type"],
        "titulo": pagina["titulo"],
        "descricao": pagina["descricao"],
        "h1": pagina["h1"],
        "h2": pagina["h2"],
        "links": pagina["links"][:max_links],
        "imagens": pagina["imagens"],
        "texto": pagina["texto"][:max_texto],
    }



if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)